(function (root, factory) {
  const data = factory();

  if (typeof module === "object" && module.exports) {
    module.exports = data;
  } else {
    root.EnergyLandingData = data;
  }
})(typeof window !== "undefined" ? window : globalThis, function () {
  const company = {
    name: "Energy Logistics LLC",
    legalName: "Energy Logistics LLC",
    phone: "+12064462631",
    phoneDisplay: "+1 (206) 446-2631",
    dispatchEmail: "dispatch@energylog.org",
    hrEmail: "hrenergylog@gmail.com",
    website: "https://energylogisticsllc.com",
    baseCity: "Black Diamond",
    baseState: "WA",
    slogan: "Driven by Reliability. Powered by Opportunity.",
  };

  const cities = [
    {
      slug: "seattle-wa",
      name: "Seattle",
      state: "WA",
      market: "Seattle freight market",
      localPhrase: "from the Duwamish industrial corridor, SoDo warehouses, Port of Seattle activity, and Kent Valley distribution lanes",
      hubs: ["Port of Seattle", "SoDo", "Duwamish industrial corridor", "Kent Valley"],
      corridors: ["I-5", "I-90", "SR 99", "SR 167"],
      useCases: ["food distributors", "port-adjacent warehouses", "retail replenishment", "regional produce programs"],
    },
    {
      slug: "tacoma-wa",
      name: "Tacoma",
      state: "WA",
      market: "Tacoma freight market",
      localPhrase: "near the Port of Tacoma, Tideflats terminals, Fife warehouses, and South Sound distribution operations",
      hubs: ["Port of Tacoma", "Tacoma Tideflats", "Fife", "Lakewood industrial area"],
      corridors: ["I-5", "SR 167", "SR 512", "SR 18"],
      useCases: ["import freight", "grocery distribution", "cold storage transfers", "brokered truckload freight"],
    },
    {
      slug: "kent-wa",
      name: "Kent",
      state: "WA",
      market: "Kent Valley freight market",
      localPhrase: "through the Kent Valley, West Valley Highway, East Valley Highway, and nearby Tukwila distribution corridors",
      hubs: ["Kent Valley", "West Valley Highway", "East Valley Highway", "Tukwila"],
      corridors: ["SR 167", "I-5", "I-405", "SR 516"],
      useCases: ["warehouse replenishment", "food service freight", "scheduled truckload lanes", "regional distribution"],
    },
    {
      slug: "auburn-wa",
      name: "Auburn",
      state: "WA",
      market: "Auburn freight market",
      localPhrase: "around Auburn industrial parks, Algona-Pacific warehousing, the Green River Valley, and South King County lanes",
      hubs: ["Auburn industrial district", "Algona-Pacific", "Green River Valley", "Outlet Collection area"],
      corridors: ["SR 167", "SR 18", "I-5", "Auburn Way"],
      useCases: ["cross-dock freight", "manufacturing inputs", "food and beverage loads", "dedicated lane support"],
    },
    {
      slug: "fife-wa",
      name: "Fife",
      state: "WA",
      market: "Fife and Port of Tacoma freight market",
      localPhrase: "between Fife warehouses, Port of Tacoma terminals, Puyallup Valley facilities, and I-5 South Sound freight lanes",
      hubs: ["Fife warehouses", "Port of Tacoma", "Puyallup Valley", "Milton industrial area"],
      corridors: ["I-5", "SR 167", "SR 99", "SR 509"],
      useCases: ["port dray-adjacent truckload moves", "cold-chain staging", "retail distribution", "broker capacity coverage"],
    },
    {
      slug: "sumner-wa",
      name: "Sumner",
      state: "WA",
      market: "Sumner-Pacific distribution market",
      localPhrase: "serving the Sumner-Pacific warehouse district, Puyallup Valley, and east Pierce County logistics operations",
      hubs: ["Sumner-Pacific warehouse district", "Puyallup Valley", "Bonney Lake access", "Pierce County industrial parks"],
      corridors: ["SR 167", "SR 410", "SR 512", "I-5"],
      useCases: ["retail DC freight", "food distribution", "scheduled outbound loads", "temperature-sensitive transfers"],
    },
    {
      slug: "puyallup-wa",
      name: "Puyallup",
      state: "WA",
      market: "Puyallup Valley freight market",
      localPhrase: "near Puyallup Valley food operations, South Hill distribution routes, Fife access points, and Pierce County warehouses",
      hubs: ["Puyallup Valley", "South Hill", "Fife access", "Pierce County warehouses"],
      corridors: ["SR 512", "SR 167", "SR 410", "I-5"],
      useCases: ["produce freight", "grocery supply", "regional delivery lanes", "seasonal food programs"],
    },
    {
      slug: "spokane-wa",
      name: "Spokane",
      state: "WA",
      market: "Inland Northwest freight market",
      localPhrase: "across Spokane Valley, West Plains, Airway Heights, and Inland Northwest distribution corridors",
      hubs: ["Spokane Valley", "West Plains", "Airway Heights", "Inland Empire Way"],
      corridors: ["I-90", "US 2", "US 395", "SR 904"],
      useCases: ["long-haul freight", "regional food distribution", "cross-state lanes", "warehouse replenishment"],
    },
    {
      slug: "vancouver-wa",
      name: "Vancouver",
      state: "WA",
      market: "Vancouver and Columbia River freight market",
      localPhrase: "around the Port of Vancouver, Columbia Business Center, Fruit Valley, and Columbia River logistics corridors",
      hubs: ["Port of Vancouver USA", "Columbia Business Center", "Fruit Valley", "Orchards industrial area"],
      corridors: ["I-5", "I-205", "SR 14", "Columbia River crossings"],
      useCases: ["Portland metro freight", "food and beverage shipments", "warehouse transfers", "interstate truckload lanes"],
    },
    {
      slug: "portland-or",
      name: "Portland",
      state: "OR",
      market: "Portland freight market",
      localPhrase: "near Rivergate, Swan Island, Columbia Corridor warehouses, and Portland metro distribution facilities",
      hubs: ["Rivergate", "Swan Island", "Columbia Corridor", "Port of Portland"],
      corridors: ["I-5", "I-84", "I-205", "US 30"],
      useCases: ["regional truckload freight", "cold-chain distribution", "consumer goods freight", "food service replenishment"],
    },
    {
      slug: "everett-wa",
      name: "Everett",
      state: "WA",
      market: "Everett and Snohomish County freight market",
      localPhrase: "serving Paine Field industrial activity, Port of Everett access, Highway 99 warehouses, and north Puget Sound lanes",
      hubs: ["Port of Everett", "Paine Field", "Highway 99 corridor", "Marysville industrial area"],
      corridors: ["I-5", "US 2", "SR 526", "SR 529"],
      useCases: ["manufacturing freight", "regional distribution", "food transportation", "north-south truckload coverage"],
    },
    {
      slug: "bellevue-wa",
      name: "Bellevue",
      state: "WA",
      market: "Bellevue and Eastside freight market",
      localPhrase: "supporting Eastside commercial receivers, Bel-Red business districts, Factoria access, and I-405 freight routes",
      hubs: ["Bel-Red corridor", "Factoria", "Eastgate", "I-405 business districts"],
      corridors: ["I-405", "I-90", "SR 520", "I-5 connections"],
      useCases: ["retail and hospitality supply", "scheduled business deliveries", "food service freight", "regional truckload moves"],
    },
    {
      slug: "renton-wa",
      name: "Renton",
      state: "WA",
      market: "Renton and South King County freight market",
      localPhrase: "near the Renton industrial area, Tukwila warehouses, Valley Medical corridor, and SR 167 freight lanes",
      hubs: ["Renton industrial area", "Tukwila warehouses", "Southcenter logistics area", "Valley Medical corridor"],
      corridors: ["I-405", "SR 167", "I-5", "SR 900"],
      useCases: ["warehouse delivery", "food and beverage freight", "scheduled regional lanes", "brokered freight coverage"],
    },
    {
      slug: "olympia-wa",
      name: "Olympia",
      state: "WA",
      market: "Olympia and South Sound freight market",
      localPhrase: "around Tumwater industrial areas, Lacey distribution sites, Port of Olympia access, and I-5 South Sound lanes",
      hubs: ["Tumwater industrial area", "Lacey distribution sites", "Port of Olympia", "South Sound logistics corridors"],
      corridors: ["I-5", "US 101", "SR 8", "SR 510"],
      useCases: ["statewide distribution", "food transportation", "long-haul staging", "regional replenishment"],
    },
  ];

  const services = [
    {
      slug: "freight-transportation",
      name: "Freight Transportation",
      noun: "freight transportation",
      headlineNoun: "Freight Transportation Company",
      routeType: "freight",
      titlePrefix: "Freight Transportation Company",
      description: "Asset-based truckload transportation for shippers and brokers that need accountable capacity, clear dispatch communication, and reliable pickup-to-delivery execution.",
      benefits: ["Asset-based carrier support", "Dispatch updates during the load cycle", "Lower 48 service except New York", "Professional handling for shipper and broker freight"],
      faqs: [
        ["Does Energy Logistics handle brokered freight?", "Yes. Energy Logistics LLC works with freight brokers as an asset-based motor carrier and supports load updates, appointment details, and tracking requirements."],
        ["What information helps dispatch quote freight?", "Origin, destination, pickup date, delivery appointment, commodity, weight, trailer type, temperature needs, and tracking requirements help dispatch review capacity quickly."],
      ],
    },
    {
      slug: "refrigerated-freight",
      name: "Refrigerated Freight",
      noun: "refrigerated freight",
      headlineNoun: "Refrigerated Freight Carrier",
      routeType: "freight",
      titlePrefix: "Refrigerated Freight Carrier",
      description: "Reefer capacity for temperature-sensitive shipments, food products, beverages, produce, dairy, meat, and other loads where timing and product condition matter.",
      benefits: ["Temperature-controlled freight focus", "Food and beverage experience", "Responsive dispatch communication", "Carrier packet access after broker verification"],
      faqs: [
        ["Do you provide refrigerated freight capacity?", "Yes. Refrigerated freight is a primary focus for Energy Logistics LLC, including food, beverage, produce, dairy, meat, and frozen shipments."],
        ["Can brokers request tracking support?", "Yes. Dispatch can support modern freight visibility expectations and load communication throughout the shipment."],
      ],
    },
    {
      slug: "frozen-goods-transportation",
      name: "Frozen Goods Transportation",
      noun: "frozen goods transportation",
      headlineNoun: "Frozen Goods Transportation Carrier",
      routeType: "freight",
      titlePrefix: "Frozen Goods Transportation",
      description: "Cold-chain transportation support for frozen commodities that require careful appointment planning, clean communication, and dependable reefer execution.",
      benefits: ["Frozen food logistics support", "Appointment-focused dispatch", "Cold-chain freight communication", "Shipper and broker friendly process"],
      faqs: [
        ["What frozen goods can be reviewed for transport?", "Dispatch can review frozen food, packaged frozen products, and other temperature-sensitive commodities based on lane, schedule, and equipment availability."],
        ["How should frozen load details be submitted?", "Include temperature requirements, pickup and delivery windows, weight, packaging, origin, destination, and any tracking or appointment instructions."],
      ],
    },
    {
      slug: "dry-van-freight",
      name: "Dry Van Freight",
      noun: "dry van freight",
      headlineNoun: "Dry Van Freight Carrier",
      routeType: "freight",
      titlePrefix: "Dry Van Freight Carrier",
      description: "Dry van truckload support for general commodities, retail freight, packaged goods, and lanes where reliable carrier communication matters.",
      benefits: ["General commodity support", "Truckload dispatch coordination", "Regional and long-haul lane review", "Broker-ready carrier communication"],
      faqs: [
        ["Does Energy Logistics review dry van freight?", "Yes. While refrigerated freight is a core focus, dry van freight opportunities can be reviewed by lane, commodity, and equipment availability."],
        ["What dry van freight is a good fit?", "Packaged goods, retail replenishment, general freight, and scheduled truckload moves are typical dry van use cases to send dispatch for review."],
      ],
    },
    {
      slug: "general-freight",
      name: "General Freight",
      noun: "general freight",
      headlineNoun: "General Freight Carrier",
      routeType: "freight",
      titlePrefix: "General Freight Carrier",
      description: "General freight transportation for commercial shipments that need dependable capacity, straightforward coordination, and clear carrier accountability.",
      benefits: ["Commercial truckload support", "Flexible commodity review", "Direct shipper and broker communication", "Experienced dispatch coordination"],
      faqs: [
        ["What general freight can be considered?", "Dispatch can review general freight based on commodity, lane, trailer needs, weight, schedule, and receiver requirements."],
        ["Is Energy Logistics a broker?", "No. Energy Logistics LLC is an asset-based motor carrier, not a freight broker."],
      ],
    },
    {
      slug: "food-transportation",
      name: "Food Transportation",
      noun: "food transportation",
      headlineNoun: "Food Transportation Carrier",
      routeType: "freight",
      titlePrefix: "Food Transportation Carrier",
      description: "Transportation support for food shippers, distributors, grocery programs, food service suppliers, and brokers moving temperature-sensitive or scheduled food freight.",
      benefits: ["Food and beverage freight focus", "Reefer-friendly dispatch workflow", "Appointment and receiver coordination", "Support for distributor and broker lanes"],
      faqs: [
        ["Do you move food freight?", "Yes. Energy Logistics LLC supports food transportation, including refrigerated and frozen freight, beverages, produce, dairy, and related scheduled loads."],
        ["Can food distributors request recurring lanes?", "Yes. Dispatch can review recurring food distribution lanes, dedicated lane needs, and truckload shipment opportunities."],
      ],
    },
    {
      slug: "dedicated-lanes",
      name: "Dedicated Lanes",
      noun: "dedicated lanes",
      headlineNoun: "Dedicated Freight Lane Carrier",
      routeType: "freight",
      titlePrefix: "Dedicated Freight Lanes",
      description: "Dedicated lane review for shippers and brokers that need repeatable truckload capacity, consistent communication, and a carrier partner that understands the route.",
      benefits: ["Repeat lane review", "Consistent dispatch contact", "Useful for food and retail programs", "Lower 48 coverage except New York"],
      faqs: [
        ["Can Energy Logistics support dedicated lanes?", "Yes. Dispatch can review recurring or dedicated lane opportunities based on schedule, freight type, origin, destination, and equipment fit."],
        ["What makes a lane a good dedicated fit?", "Repeat volume, predictable pickup and delivery windows, clear receiver requirements, and lane consistency help determine whether dedicated support is practical."],
      ],
    },
    {
      slug: "long-haul-trucking",
      name: "Long-Haul Trucking",
      noun: "long-haul trucking",
      headlineNoun: "Long-Haul Trucking Carrier",
      routeType: "freight",
      titlePrefix: "Long-Haul Trucking Carrier",
      description: "Long-haul transportation for freight moving across state lines, with an emphasis on professional dispatch, clear check-ins, and dependable truckload execution.",
      benefits: ["Interstate truckload support", "Lower 48 service except New York", "Good fit for refrigerated and general freight", "Communication for broker operations"],
      faqs: [
        ["What long-haul areas does Energy Logistics serve?", "Energy Logistics LLC serves the lower 48 states except New York, subject to lane, schedule, and capacity review."],
        ["Can long-haul refrigerated loads be requested?", "Yes. Long-haul refrigerated freight can be submitted to dispatch with temperature, commodity, pickup, and delivery details."],
      ],
    },
    {
      slug: "cdl-driver-jobs",
      name: "CDL Driver Jobs",
      noun: "CDL driver jobs",
      headlineNoun: "CDL Driver Jobs",
      routeType: "driver",
      titlePrefix: "CDL Driver Jobs",
      description: "CDL driver career opportunities with weekly pay, paid training, flexible opportunities, and openings for motivated drivers including new CDL graduates.",
      benefits: ["New CDL graduates welcome", "Paid training", "Weekly pay", "Flexible opportunities", "Professional dispatch support"],
      faqs: [
        ["Are new CDL graduates welcome?", "Yes. Energy Logistics LLC welcomes new CDL graduates and offers paid training opportunities."],
        ["How do drivers apply?", "Use the driver application button on this page or email HR with your contact information, CDL status, experience, and availability."],
      ],
    },
    {
      slug: "owner-operator-opportunities",
      name: "Owner-Operator Opportunities",
      noun: "owner-operator opportunities",
      headlineNoun: "Owner-Operator Opportunities",
      routeType: "driver",
      titlePrefix: "Owner-Operator Opportunities",
      description: "Owner-operator opportunities built around flexible dispatch, weekly settlements, a 90/10 split, trailer rental options, fuel card support, and 24/7 dispatch communication.",
      benefits: ["90/10 split", "No forced dispatch", "Weekly settlements", "Fuel card program", "Trailer rental program", "24/7 dispatch support"],
      faqs: [
        ["What is the owner-operator program split?", "Energy Logistics LLC lists a 90/10 split for owner-operator opportunities."],
        ["Is dispatch forced?", "No. The owner-operator program is built with no forced dispatch and flexible opportunity review."],
      ],
    },
  ];

  const routeFamilies = [
    { prefix: "freight-carrier", cityOnly: true, serviceSlug: "freight-transportation", label: "Freight Carrier" },
    { prefix: "refrigerated-freight", cityOnly: true, serviceSlug: "refrigerated-freight", label: "Refrigerated Freight" },
    { prefix: "dry-van-freight", cityOnly: true, serviceSlug: "dry-van-freight", label: "Dry Van Freight" },
    { prefix: "driver-jobs", cityOnly: true, serviceSlug: "cdl-driver-jobs", label: "Driver Jobs" },
    { prefix: "services", cityOnly: false, label: "Services" },
  ];

  return { company, cities, services, routeFamilies };
});
